import React,{useEffect,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Activity,AlertTriangle,Box,Clock3,DoorClosed,LockKeyhole,Radio,ShieldCheck, Thermometer, UserRound, Wifi, Droplets} from 'lucide-react'
import './index.css'

const API='http://localhost:8000/api'

function Card({icon:Icon,label,value,sub,alert=false}){return <div className={`rounded-2xl border bg-white p-5 shadow-sm ${alert?'border-red-200':''}`}><div className="flex items-center justify-between"><div className="rounded-xl bg-slate-100 p-2.5"><Icon size={21}/></div>{alert&&<span className="rounded-full bg-red-50 px-2.5 py-1 text-xs font-semibold text-red-600">Alert</span>}</div><div className="mt-4 text-sm text-slate-500">{label}</div><div className="mt-1 text-2xl font-bold tracking-tight">{value}</div>{sub&&<div className="mt-1 text-xs text-slate-400">{sub}</div>}</div>}

function Status({ok,children}){return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${ok?'bg-emerald-50 text-emerald-700':'bg-red-50 text-red-700'}`}><span className={`h-2 w-2 rounded-full ${ok?'bg-emerald-500':'bg-red-500'}`}/>{children}</span>}

function eventLabel(e){const map={EVIDENCE_SCAN:'Evidence scanned',OFFICER_SCAN:'Officer scanned',DOOR_OPEN:'Locker opened',DOOR_CLOSE:'Locker closed',UNAUTHORIZED_ACCESS:'Unauthorized access',TEMPERATURE_READING:'Temperature reading',HEARTBEAT:'Hardware heartbeat'};return map[e.event_type]||e.event_type}
function eventClass(t){if(t==='UNAUTHORIZED_ACCESS')return 'text-red-700 bg-red-50';if(t==='EVIDENCE_SCAN'||t==='OFFICER_SCAN')return 'text-blue-700 bg-blue-50';return 'text-slate-700 bg-slate-100'}
function time(v){if(!v)return '—';return new Date(v).toLocaleString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}

function App(){
 const [data,setData]=useState(null); const [online,setOnline]=useState(false); const [loading,setLoading]=useState(true)
 async function load(){try{const r=await fetch(`${API}/dashboard`);if(!r.ok)throw new Error();const j=await r.json();setData(j);setOnline(true)}catch{setOnline(false)}finally{setLoading(false)}}
 useEffect(()=>{load();const id=setInterval(load,3000);return()=>clearInterval(id)},[])
 const d=data||{}; const recent=d.recent_events||[]
 return <div className="min-h-screen bg-slate-50">
  <header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4 lg:px-8"><div><div className="flex items-center gap-3"><div className="rounded-xl bg-slate-900 p-2 text-white"><LockKeyhole size={21}/></div><div><h1 className="text-xl font-bold">EvidenceVault</h1><p className="text-xs text-slate-500">Smart Evidence Monitoring Dashboard</p></div></div></div><Status ok={online}>{online?'System connected':'Backend offline'}</Status></div></header>
  <main className="mx-auto max-w-7xl space-y-6 px-5 py-6 lg:px-8">
   <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card icon={Box} label="Total Evidence" value={d.total_evidence??'—'} sub="Registered evidence"/><Card icon={Radio} label="RFID Scans Today" value={d.scans_today??'—'} sub="Automatic hardware events"/><Card icon={Thermometer} label="Temperature" value={d.temperature!=null?`${d.temperature} °C`:'—'} sub="Latest sensor reading"/><Card icon={AlertTriangle} label="Unauthorized Today" value={d.unauthorized_today??'—'} sub="Security events" alert={Number(d.unauthorized_today)>0}/></section>
   <section className="grid gap-6 lg:grid-cols-3">
    <div className="rounded-2xl border bg-white p-6 shadow-sm lg:col-span-1"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">Live Hardware</h2><p className="text-sm text-slate-500">Latest device status</p></div><Wifi size={20}/></div><div className="space-y-3"><div className="flex items-center justify-between rounded-xl bg-slate-50 p-4"><span className="flex items-center gap-3 text-sm"><Radio size={18}/> RFID Reader</span><Status ok={online}>{online?'Online':'Offline'}</Status></div><div className="flex items-center justify-between rounded-xl bg-slate-50 p-4"><span className="flex items-center gap-3 text-sm"><DoorClosed size={18}/> Locker Door</span><span className="font-semibold text-sm">{d.door_status||'Unknown'}</span></div><div className="flex items-center justify-between rounded-xl bg-slate-50 p-4"><span className="flex items-center gap-3 text-sm"><Droplets size={18}/> Humidity</span><span className="font-semibold text-sm">{d.humidity!=null?`${d.humidity} %`:'—'}</span></div><div className="flex items-center justify-between rounded-xl bg-slate-50 p-4"><span className="flex items-center gap-3 text-sm"><Clock3 size={18}/> Last update</span><span className="font-semibold text-sm">{time(d.last_event_at)}</span></div></div></div>
    <div className="rounded-2xl border bg-white p-6 shadow-sm lg:col-span-2"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-bold">Recent Hardware Activity</h2><p className="text-sm text-slate-500">Automatically received from ESP32</p></div><Activity size={20}/></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b text-xs uppercase text-slate-400"><tr><th className="pb-3">Time</th><th className="pb-3">Event</th><th className="pb-3">RFID</th><th className="pb-3">Details</th></tr></thead><tbody>{loading?<tr><td colSpan="4" className="py-8 text-center text-slate-400">Loading...</td></tr>:recent.length===0?<tr><td colSpan="4" className="py-8 text-center text-slate-400">No hardware events yet.</td></tr>:recent.map((e,i)=><tr key={i} className="border-b last:border-0"><td className="py-3 whitespace-nowrap text-slate-500">{time(e.timestamp)}</td><td className="py-3"><span className={`rounded-lg px-2 py-1 text-xs font-semibold ${eventClass(e.event_type)}`}>{eventLabel(e)}</span></td><td className="py-3 font-mono text-xs">{e.rfid_uid||'—'}</td><td className="py-3 text-slate-600">{e.message||e.evidence_id||e.door_status||'—'}</td></tr>)}</tbody></table></div></div>
   </section>
   <section className="grid gap-6 lg:grid-cols-2">
    <div className="rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><ShieldCheck size={21}/><div><h2 className="font-bold">Security Monitoring</h2><p className="text-sm text-slate-500">Automatic access monitoring</p></div></div>{recent.filter(e=>e.event_type==='UNAUTHORIZED_ACCESS').slice(0,3).map((e,i)=><div key={i} className="mb-3 rounded-xl border border-red-200 bg-red-50 p-4"><div className="flex items-center justify-between"><div className="font-semibold text-red-800">Unauthorized access detected</div><span className="text-xs text-red-600">{time(e.timestamp)}</span></div><div className="mt-2 text-sm text-red-700">RFID: <span className="font-mono">{e.rfid_uid||'Unknown'}</span> · {e.location||'Evidence Locker'}</div></div>)}{recent.filter(e=>e.event_type==='UNAUTHORIZED_ACCESS').length===0&&<div className="rounded-xl bg-emerald-50 p-5 text-sm text-emerald-700">No unauthorized access events in the latest activity.</div>}</div>
    <div className="rounded-2xl border bg-white p-6 shadow-sm"><div className="mb-5 flex items-center gap-3"><UserRound size={21}/><div><h2 className="font-bold">Latest Evidence Scan</h2><p className="text-sm text-slate-500">Information detected from RFID</p></div></div>{recent.find(e=>e.event_type==='EVIDENCE_SCAN')?<div className="grid gap-3 sm:grid-cols-2"><Info label="Evidence ID" value={recent.find(e=>e.event_type==='EVIDENCE_SCAN').evidence_id||'Unknown'}/><Info label="RFID UID" value={recent.find(e=>e.event_type==='EVIDENCE_SCAN').rfid_uid||'—'}/><Info label="Location" value={recent.find(e=>e.event_type==='EVIDENCE_SCAN').location||'Evidence Locker'}/><Info label="Time" value={time(recent.find(e=>e.event_type==='EVIDENCE_SCAN').timestamp)}/></div>:<div className="rounded-xl bg-slate-50 p-5 text-sm text-slate-500">No evidence RFID scan received yet.</div>}</div>
   </section>
   <footer className="pb-4 text-center text-xs text-slate-400">EvidenceVault · React + FastAPI + MongoDB · Hardware data refreshes every 3 seconds</footer>
  </main>
 </div>
}
function Info({label,value}){return <div className="rounded-xl bg-slate-50 p-4"><div className="text-xs text-slate-400">{label}</div><div className="mt-1 font-semibold">{value}</div></div>}
createRoot(document.getElementById('root')).render(<App/>)
